<?php

use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var yii\gii\generators\crud\Generator $generator
 */

$urlParams = $generator->generateUrlParams();

echo "<?php\n";
?>

/**
* Autogenerated From GII
* modified by Defri Indra M
* 2021
*/

use yii\helpers\Html;

/**
* @var yii\web\View $this
* @var <?= ltrim($generator->modelClass, '\\') ?> $model
*/

$this->title = <?=
$generator->generateString(Inflector::camel2words(
    StringHelper::basename($generator->modelClass)
)) ?> . ' ' . $model-><?= $generator->getNameAttribute() ?> . ', ' . <?= $generator->generateString('Ubah') ?>;
$this->params['breadcrumbs'][] = ['label' => <?=
$generator->generateString(Inflector::camel2words(
    StringHelper::basename($generator->modelClass)
)) ?> , 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model-><?= $generator->getNameAttribute() ?>, 'url' => ['view', <?= $urlParams ?>]];
$this->params['breadcrumbs'][] = <?= $generator->generateString('Ubah') ?>;
?>

<div class="row">
    <div class="col-md-12">
        <?= "<?php" ?> if(Yii::$app->request->isAjax == false) : ?>
        <!-- <p>
            <?= "<?= " ?>Html::a(<?= $generator->generateString('Kembali') ?>, \yii\helpers\Url::previous(), ['class' => 'btn btn-default']) ?>
        </p> -->
        <div class="card m-b-30">
            <div class="card-body">
                <?= "<?php" ?> endif ?>
                <?= "<?php " ?>echo $this->render('_form', $model->render()); ?>
                <?= "<?php" ?> if(Yii::$app->request->isAjax == false) : ?>
            </div>
        </div>
        <?= "<?php" ?> endif ?>
    </div>
</div>