<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\ModalButton;
use kartik\daterange\DateRangePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\BookingDataSearch $searchModel
 */

$this->title = Yii::t('cruds', 'Booking Data');
$this->params['breadcrumbs'][] = $this->title;
?>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::className(),
                            'firstPageLabel' => Yii::t('cruds', 'First'),
                            'lastPageLabel'  => Yii::t('cruds', 'Last')
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-borderless table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [

                            \app\components\ActionAjaxButton::getButtons(['template' => '{view}']),

                            [
                                'attribute' => 'type',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'jenis_layanan',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'tanggal_kedatangan',
                                'format' => 'iddate',
                                'filter' => DateRangePicker::widget([
                                    'model' => $searchModel,
                                    'attribute' => 'tanggal_kedatangan',
                                    'convertFormat' => true,
                                    'pluginOptions' => [
                                        'timePicker' => false,
                                        'timePickerIncrement' => 30,
                                        'locale' => [
                                            'format' => 'Y-m-d'
                                        ]
                                    ]
                                ]),
                            ],
                            [
                                'attribute' => 'jam_kedatangan',
                                'format' => 'raw',
                                'filter' => false,
                                'value' => function ($model) {
                                    // split time and label

                                    if ($model->jam_kedatangan === "") {
                                        return "<span class='badge badge-primary'>-</span>";
                                    }

                                    $time = explode(',', $model->jam_kedatangan);
                                    $result = "";

                                    foreach ($time as $key => $value) {
                                        $result .= "<span class='badge badge-primary'>$value</span>";
                                    }
                                    return $result;
                                }
                            ],
                            [
                                'attribute' => 'nama_perusahaan',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'nama_penanggungjawab',
                                'format' => 'text',
                            ],
                            // [
                            //     'attribute' => 'nomor_penerbangan',
                            //     'format' => 'text',
                            // ],
                            /*[
            'attribute' => 'nomor_telepon',
            'format' => 'text',
        ],*/
                            /*[
            'attribute' => 'jumlah_penumpang',
            'format' => 'text',
        ],*/
                            /*[
            'attribute' => 'email',
            'format' => 'email',
        ],*/
                            /*[
            'attribute' => 'creatad_at',
            'format' => 'iddate',
        ],*/
                            /*[
            'attribute' => 'id',
            'format' => 'text',
        ],*/
                            // \app\components\ActionAjaxButton::getButtons(['template' => '{delete}']),
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>