<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\annex\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\BookingData $model
 */

$this->title = Yii::t('cruds', 'Booking Data') . ' : ' . $model->id;
?>
<div class="giiant-crud booking-data-view">
    <?php if (Yii::$app->request->isAjax == false) : ?>
        <!-- menu buttons -->
        <p class='pull-left'>
            <?= Html::a('<span class="fa fa-pencil"></span> ' . Yii::t('cruds', 'Ubah'), ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
            <?= Html::a('<span class="fa fa-plus"></span> ' . Yii::t('cruds', 'Tambah Baru'), ['create'], ['class' => 'btn btn-success']) ?>
        </p>
        <p class="pull-right">
            <?= Html::a('<span class="fa fa-list"></span> ' . Yii::t('cruds', 'Daftar Booking Data'), ['index'], ['class' => 'btn btn-default']) ?>
        </p>
    <?php endif ?>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-12">
            <?php if (Yii::$app->request->isAjax == false) : ?>
                <div class="card m-b-30">
                    <div class="card-body">
                    <?php endif ?>
                    <?php $this->beginBlock('app\models\BookingData'); ?>
                    <div class="table-responsive">
                        <?= DetailView::widget([
                            'model' => $model,
                            'options' => ['class' => 'table table-striped table-borderless'],
                            'attributes' => [
                                [
                                    'attribute' => 'type',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'jenis_layanan',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'tanggal_kedatangan',
                                    'format' => 'iddate',
                                ],
                                [
                                    'attribute' => 'jam_kedatangan',
                                    'format' => 'raw',
                                    'filter' => false,
                                    'value' => function ($model) {
                                        // split time and label
    
                                        if ($model->jam_kedatangan === "") {
                                            return "<span class='badge badge-primary'>-</span> ";
                                        }
    
                                        $time = explode(',', $model->jam_kedatangan);
                                        $result = "";
    
                                        foreach ($time as $key => $value) {
                                            $result .= "<span class='badge badge-primary'>$value</span> ";
                                        }
                                        return $result;
                                    }
                                ],
                                [
                                    'attribute' => 'nama_perusahaan',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'nama_penanggungjawab',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'nomor_penerbangan',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'nomor_telepon',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'jumlah_penumpang',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'email',
                                    'format' => 'email',
                                ],
                                [
                                    'attribute' => 'creatad_at',
                                    'format' => 'iddate',
                                ],
                            ],
                        ]); ?>
                    </div>

                    <hr />

                    <?= Html::a(
                        '<span class="fa fa-trash"></span> ' . Yii::t('cruds', 'Delete'),
                        ['delete', 'id' => $model->id],
                        [
                            'class' => 'btn btn-danger',
                            'data-confirm' => '' . Yii::t('cruds', 'Are you sure to delete this item?') . '',
                            'data-method' => 'post',
                        ]
                    ); ?>
                    <?php $this->endBlock(); ?>



                    <?= Tabs::widget(
                        [
                            'id' => 'relation-tabs',
                            'encodeLabels' => false,
                            'items' => [
                                [
                                    'label'   => '<b class=""># ' . $model->id . '</b>',
                                    'content' => $this->blocks['app\models\BookingData'],
                                    'active'  => true,
                                ],
                            ]
                        ]
                    );
                    ?> <?php if (Yii::$app->request->isAjax == false) : ?>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>