<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\ModalButton;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\TestimoniSearch $searchModel
 */

$this->title = Yii::t('cruds', 'Testimoni');
$this->params['breadcrumbs'][] = $this->title;
?>

<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::className(),
                            'firstPageLabel' => Yii::t('cruds', 'First'),
                            'lastPageLabel'  => Yii::t('cruds', 'Last')
                        ],
                        // 'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-borderless table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [
                            \app\components\ActionAjaxButton::getButtons([
                                'template' => '{toggle}',
                                'buttons' => [
                                    'toggle' => function ($url, $model, $key) {
                                        return Html::a(
                                            '<i class="fa fa-toggle-' . ($model->show == 1 ? 'on' : 'off') . '"></i>',
                                            Url::to(['toggle', 'id' => $model->id]),
                                            [
                                                'class' => 'btn btn-sm btn-' . ($model->show == 1 ? 'success' : 'danger'),
                                                'title' => Yii::t('cruds', 'Toggle'),
                                                'data-pjax' => '0',
                                                'data-toggle' => 'tooltip',
                                                'data-confirm' => Yii::t('cruds', 'Are you sure you want to toggle this item?'),
                                                'data-method' => 'post',
                                            ]
                                        );
                                    },
                                ]
                            ]),
                            [
                                'attribute' => 'name',
                                'format' => 'text',
                                'filter' => false,
                            ],
                            [
                                'attribute' => 'text',
                                'format' => 'ntext',
                                'filter' => false,
                            ],
                            [
                                'attribute' => 'created_at',
                                'format' => 'iddate',
                                'filter' => false,
                            ],
                            /*[
            'attribute' => 'id',
            'format' => 'text',
        ],*/
                            \app\components\ActionAjaxButton::getButtons(['template' => '{delete}']),
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>