<?php
/**
 * This is the template for generating the model class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
*/
use yii\helpers\Inflector;
use yii\helpers\StringHelper;

/**
 * @var yii\web\View $this
 * @var app\template\giiant\generators\model\Generator $generator
 * @var string $tableName full table name
 * @var string $className class name
 * @var yii\db\TableSchema $tableSchema
 * @var string[] $labels list of attribute labels (name => label)
 * @var string[] $rules list of validation rules
 * @var array $relations list of relations (name => relation declaration)
 */

echo "<?php\n";

?>
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace <?= $generator->ns ?>\base;

use Yii;
<?php if (isset($translation)): ?>
use dosamigos\translateable\TranslateableBehavior;
<?php endif; ?>
<?php if (!empty($blameable)): ?>
use yii\behaviors\BlameableBehavior;
<?php endif; ?>
<?php if (!empty($timestamp)): ?>
use yii\behaviors\TimestampBehavior;
<?php endif; ?>

/**
 * This is the base-model class for table "<?= $tableName ?>".
 *
<?php foreach ($tableSchema->columns as $column): ?>
 * @property <?= "{$column->phpType} \${$column->name}\n" ?>
<?php endforeach; ?>
<?php if (!empty($relations)): ?>
 *
<?php foreach ($relations as $name => $relation): ?>
 * @property \<?=$ns?>\<?= $relation[1] . ($relation[2] ? '[]' : '') . ' $' . lcfirst($name) . "\n" ?>
<?php endforeach; ?>
<?php endif; ?>
 * @property string $aliasModel
 */
abstract class <?= $className ?> extends <?= '\\' . ltrim($generator->baseClass, '\\') . "\n" ?>
{
<?php
    $traits = $generator->baseTraits;
    if ($traits) {
        echo "use {$traits};";
    }
?>
    /**
     * BaseModel rules. 
     **/
    use \app\traits\ModelTrait;

    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

<?php
if(!empty($enum)){
?>
    /**
    * ENUM field values
    */
<?php
    foreach($enum as $column_name => $column_data){
        foreach ($column_data['values'] as $enum_value){
            echo '    const ' . $enum_value['const_name'] . ' = \'' . $enum_value['value'] . '\';' . PHP_EOL;
        }
    }
?>
    var $enum_labels = false;
<?php
}
?>
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '<?= $tableName ?>';
    }
<?php if ($generator->db !== 'db'): ?>

    /**
     * @return \yii\db\Connection the database connection used by this AR class.
     */
    public static function getDb()
    {
        return Yii::$app->get('<?= $generator->db ?>');
    }
<?php endif; ?>
<?php if (isset($translation) || !empty($blameable) || !empty($timestamp) || true): ?>

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => \app\components\behaviors\UUIDBehavior::class,
                'model' => get_called_class(),
                'primaryKey' => 'id',
            ],
<?php if (!empty($blameable)): ?>
            [
                'class' => BlameableBehavior::className(),
<?php if ($blameable['createdByAttribute'] !== 'created_by'): ?>
                'createdByAttribute' => <?= $blameable['createdByAttribute'] ? "'" . $blameable['createdByAttribute'] . "'" : 'false' ?>,
<?php endif; ?>
<?php if ($blameable['updatedByAttribute'] !== 'updated_by'): ?>
                'updatedByAttribute' => <?= $blameable['updatedByAttribute'] ? "'" . $blameable['updatedByAttribute'] . "'" : 'false' ?>,
<?php endif; ?>
            ],
<?php endif; ?>
<?php if (!empty($timestamp)): ?>
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => <?= $timestamp['createdAtAttribute'] ? "'" . $timestamp['createdAtAttribute'] . "'" : 'false' ?>,
                'updatedAtAttribute' => <?= $timestamp['updatedAtAttribute'] ? "'" . $timestamp['updatedAtAttribute'] . "'" : 'false' ?>,
                'value' => date("Y-m-d H:i:s"),
            ],
<?php endif; ?>
<?php if (isset($translation)): ?>
            'translatable' => [
                'class' => TranslateableBehavior::className(),
                // in case you renamed your relation, you can setup its name
                // 'relation' => 'translations',
<?php if ($generator->languageCodeColumn !== 'language'): ?>
                'languageField' => '<?= $generator->languageCodeColumn ?>',
<?php endif; ?>
                'translationAttributes' => [
                    <?= "'" . implode("',\n                    '", $translation['fields']) . "'\n" ?>
                ],
            ],
<?php endif; ?>
        ];
    }
<?php endif; ?>

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [<?= "\n            " . implode(",\n            ", $rules) . "\n        " ?>];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
<?php 
    $blacklist = [
        "created_at" => $generator->generateString('Dibuat pada'),
        "created_by" => $generator->generateString('Dibuat oleh'),
        "updated_at" => $generator->generateString('Diubah Pada'),
        "updated_by" => $generator->generateString('Diubah oleh'),
        "deleted_at" => $generator->generateString('Dihapus pada'),
        "deleted_by" => $generator->generateString('Dihapus oleh'),
    ];
    foreach ($labels as $name => $label): 
        if(isset($blacklist[$name])): ?>
            <?= "'$name' => " . $blacklist[$name] . ",\n" ?>
<?php else: ?>
            <?= "'$name' => " . str_replace(["Id "," ID"],["",""],$generator->generateString($label)) . ",\n" ?>
<?php endif ?>
<?php endforeach; ?>
        ];
    }
<?php if (!empty($hints)): ?>

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
<?php foreach ($hints as $name => $hint): ?>
            <?= "'$name' => " . $generator->generateString($hint) . ",\n" ?>
<?php endforeach; ?>
        ]);
    }
<?php endif; ?>
<?php foreach ($relations as $name => $relation): ?>

    /**
     * @return \yii\db\ActiveQuery
     */
    public function get<?= $name ?>()
    {
        <?= $relation[0] . "\n" ?>
    }
<?php endforeach; ?>

<?php if (isset($translation)): ?>
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTranslations()
    {
        <?= $translation['code'] . "\n"?>
    }
<?php endif; ?>

<?php if ($queryClassName): ?>
    <?php
    $queryClassFullName = ($generator->ns .'\\base' === $generator->queryNs) ? $queryClassName : '\\' . $generator->queryNs . '\\' . $queryClassName;
    echo "\n";
    ?>
    /**
     * @inheritdoc
     * @return <?= $queryClassFullName ?> the active query used by this AR class.
     */
    public static function find()
    {
        return new <?= $queryClassFullName ?>(get_called_class());
    }
<?php endif; ?>

<?php
    foreach($enum as $column_name => $column_data){
?>

    /**
     * get column <?php echo $column_name?> enum value label
     * @param string $value
     * @return string
     */
    public static function <?php echo $column_data['func_get_label_name']?>($value){
        $labels = self::<?php echo $column_data['func_opts_name']?>();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column <?php echo $column_name?> ENUM value labels
     * @return array
     */
    public static function <?php echo $column_data['func_opts_name']?>()
    {
        return [
<?php
        foreach($column_data['values'] as $k => $value){
            if ($generator->enableI18N) {
                echo '            '.'self::' . $value['const_name'] . ' => Yii::t(\'' . $generator->messageCategory . '\', self::' . $value['const_name'] . "),\n";
            } else {
                echo '            '.'self::' . $value['const_name'] . ' => self::' . $value['const_name'] . ",\n";
            }
        }
?>
        ];
    }
<?php
    }


?>


    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
<?php foreach ($labels as $name => $label): ?>
            <?= "'$name',\n" ?>
<?php endforeach; ?>
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

<?php foreach ($labels as $name => $label): ?>
        if(isset($parent['<?=$name?>'])) :
            unset($parent['<?=$name?>']);
            $parent['<?=$name?>'] = function($model) {
<?php if(strposa($name,['created_at','updated_at','dibuat_pada','diubah_pada','tanggal','date'])): ?>
                return \app\helpers\DateTimeHelper::toReadableDate($model-><?=$name?>, false);
<?php elseif(strposa($name,['gambar','image','icon'])): ?>
                return \Yii::$app->formatter->asMyImage($model-><?=$name?>, false);
<?php else: ?>
                return $model-><?=$name?>;
<?php endif ?>
            };
<?php foreach($relations as $relName=>$rel):
    if(strpos($rel[0],$name) && $name!="id"):
         $relName[0]=strtolower($relName[0]);
         $relNameAttribute=\Yii\helpers\Inflector::camel2id($relName,"_");?>
            $parent['_<?=$relNameAttribute?>'] = function($model) {
                $rel = $model-><?=$relName?>;
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
<?php endif ?>
<?php endforeach?>
        endif;
<?php endforeach; ?>


<?php foreach($relations as $relName=>$rel):
    if($rel[2]==1): 
        $relName[0] = strtolower($relName[0]);
        $relNameAttribute = \Yii\helpers\Inflector::camel2id($relName,"_");
        $relNameAttribute = substr($relNameAttribute,0,strlen($relNameAttribute)-1);?>
    // $parent['<?=$relNameAttribute?>'] = function($model) {
    //     $rel = $model-><?=$relName?>;
    //     if($rel) :
    //         return $rel;
    //     endif;
    //     return null;
    // };
<?php endif ?>
<?php endforeach?>

        return $parent;
    }


    public static function faker($count = 10){
        $faker= \Faker\Factory::create();
        $faker->addProvider(new \app\components\faker\provider\MyImage($faker));
        $data = [];
        $maxId = static::find()->max('id');

        // relational data
<?php foreach ($tableSchema->columns as $column) :
        foreach ($relations as $relName=>$relation) :
            if ($relation[2] == 0) :
                $rel = explode("']",explode("=> '",$relation[0])[1])[0];
                $_class_rel = explode("hasOne(",explode("::className()",$relation[0])[0])[1];
                if ($rel == $column->name):
                    $relName[0] = strtolower($relName[0]);?>
        $relational<?=$relName?> = \app\components\Constant::getIDs(<?=$_class_rel?>::find()->select('id')->all(), 'id');
<?php 
            endif;
        endif;
    endforeach;
endforeach?>
        for ($i = 0; $i < $count; $i++) {
            $data[] = [ 
<?php foreach ($tableSchema->columns as $column): ?>
<?php $haveRel=0?>
<?php foreach($relations as $relName=>$relation):
        if($relation[2]==0):
            $rel=explode("']",explode("=> '",$relation[0])[1])[0];
            if($rel==$column->name):
                $relName[0]=strtolower($relName[0]);
                $haveRel=1;?>
                "<?=$column->name?>" => \app\components\Constant::getRandomFrom($relational<?=$relName?>),
<?php 
            endif;
        endif;
endforeach?>
<?php if($haveRel) continue?>
<?php if(strposa($column->name,["id"])):?>
                "<?=$column->name?>" => $faker->unique()->numberBetween($maxId, $maxId + $count),
<?php elseif(strposa($column->name,["flag"])):?>
                "<?=$column->name?>" => $faker->numberBetween(0, 1),
<?php elseif(strposa($column->name,["_at","tanggal","_pada", "last_", "waktu"])):?>
                "<?=$column->name?>" => $faker->dateTime(),
<?php elseif(strposa($column->name,["username"])):?>
                "<?=$column->name?>" => $faker->username,
<?php elseif(strposa($column->name,["name","nama"])):?>
                "<?=$column->name?>" => $faker->name,
<?php elseif(strposa($column->name,["year","tahun"])):?>
                "<?=$column->name?>" => $faker->date("Y"),
<?php elseif(strposa($column->name,["bulan","month"])):?>
                "<?=$column->name?>" => int($faker->month()),
<?php elseif(strposa($column->name,["title","judul"])):?>
                "<?=$column->name?>" => $faker->sentence($nbWords = 6, $variableNbWords = true),
<?php elseif(strposa($column->name,["description","deskripsi","keterangan","about","tentang"])):?>
                "<?=$column->name?>" => $faker->paragraphs($nb = 3, $asText = true),
<?php elseif(strposa($column->name,["address","alamat","lokasi"])):?>
                "<?=$column->name?>" => $faker->address,
<?php elseif(strposa($column->name,["email"])):?>
                "<?=$column->name?>" => $faker->freeEmail,
<?php elseif(strposa($column->name,["slug"])):?>
                "<?=$column->name?>" => $faker->slug,
<?php elseif(strposa($column->name,["image", "photo", "gambar", "foto"])):?>
                "<?=$column->name?>" => "tmp/". $faker->myimage($dir = \Yii::getAlias('@webroot/uploads/tmp'), $width = 640, $height = 480, "cats", false),
<?php else:?>
<?php if($column->type=="integer"):?>
                "<?=$column->name?>" => $faker->randomNumber(),
<?php elseif($column->type):?>
                "<?=$column->name?>" => $faker->text(),
<?php endif ?>
<?php endif ?>
<?php endforeach; ?>            ];
        }
        return $data;
    }

}
