<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "whywe".
 *
 * @property string $icon
 * @property string $title
 * @property string $description
 * @property integer $id
 * @property string $aliasModel
 */
abstract class Whywe extends \yii\db\ActiveRecord
{
    /**
     * BaseModel rules. 
     **/
    use \app\traits\ModelTrait;

    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'whywe';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            // [
            //     'class' => \app\components\behaviors\UUIDBehavior::class,
            //     'model' => get_called_class(),
            //     'primaryKey' => 'id',
            // ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['icon', 'title', 'description'], 'required'],
            [['description'], 'string'],
            [['icon'], 'string', 'max' => 250],
            [['title'], 'string', 'max' => 150],
            [['id'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'icon' => Yii::t('models', 'Icon'),
            'title' => Yii::t('models', 'Title'),
            'description' => Yii::t('models', 'Description'),
        ];
    }





    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            'icon',
            'title',
            'description',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

        if(isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function($model) {
                return $model->id;
            };
        endif;
        if(isset($parent['icon'])) :
            unset($parent['icon']);
            $parent['icon'] = function($model) {
                return \Yii::$app->formatter->asMyImage($model->icon, false);
            };
        endif;
        if(isset($parent['title'])) :
            unset($parent['title']);
            $parent['title'] = function($model) {
                return $model->title;
            };
        endif;
        if(isset($parent['description'])) :
            unset($parent['description']);
            $parent['description'] = function($model) {
                return $model->description;
            };
        endif;



        return $parent;
    }


    public static function faker($count = 10){
        $faker= \Faker\Factory::create();
        $faker->addProvider(new \app\components\faker\provider\MyImage($faker));
        $data = [];
        $maxId = static::find()->max('id');

        // relational data
        for ($i = 0; $i < $count; $i++) {
            $data[] = [ 
                "icon" => $faker->text(),
                "title" => $faker->sentence($nbWords = 6, $variableNbWords = true),
                "description" => $faker->paragraphs($nb = 3, $asText = true),
                "id" => $faker->unique()->numberBetween($maxId, $maxId + $count),
            ];
        }
        return $data;
    }

}
