<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\Services $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
    'id' => 'Services',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <?= $form->field($model, 'image', \app\components\Constant::COLUMN(1))->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'title', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'link', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'description', \app\components\Constant::COLUMN(1))->textarea(['rows' => 3]) ?>
    <?= $form->field($model, 'content', \app\components\Constant::COLUMN(1))->widget(\vova07\imperavi\Widget::class, [
        "settings" => [
            "lang" => "id",
            "minHeight" => 500,
            "imageUpload" => \yii\helpers\Url::to(['/blog/media/image-upload']),
            "imageManagerJson" => \yii\helpers\Url::to(['/blog/media/images-get']),
            "plugins" => [
                // register all plugins from `vendor/vova07/imperavi-redactor/plugins`
                "clips",
                "counter",
                "filemanager",
                "fontcolor",
                "fontsize",
                "fontfamily",
                "fullscreen",
                "imagemanager",
                "limiter",
                "table",
                "textdirection",
                "textexpander",
                "video",
            ]
        ]
    ]) ?>
    <div class="clearfix"></div>
</div>
<hr />
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?= Html::submitButton('<i class="fa fa-save"></i> ' . Yii::t('cruds', 'Simpan'), ['class' => 'btn btn-success']); ?>
        <?php if (Yii::$app->request->isAjax == false) : ?>
            <?= Html::a('<i class="fa fa-chevron-left"></i> ' . Yii::t('cruds', 'Kembali'), ['index'], ['class' => 'btn btn-default']) ?>
        <?php endif ?>
    </div>
</div>
<?php ActiveForm::end(); ?>